version: "3.9"
services:
  api:
    build: .
    ports: [ "${PORT:-8080}:8080" ]
    env_file: [ .env ]
    depends_on: [ mongo ]
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: [ "27017:27017" ]
    environment: { MONGO_INITDB_DATABASE: magicstream }
    volumes: [ "mongo_data:/data/db" ]
  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    ports: [ "8081:8081" ]
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
volumes: { mongo_data: {} }
